FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y \
        build-essential \
        curl \
        git \
        libssl-dev \
        libffi-dev \
        libsqlite3-dev \
        python3 \
        python3-pip \
        python3-venv \
        python3-dev \
        unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# RUN pip3 install --no-cache-dir pipx \
#     && pipx ensurepath \
#     && pipx install black \
#     && pipx install flake8 \
#     # && pipx install mypy \
#     # && pipx install ipython \
#     && pipx install pytest

RUN useradd -ms /bin/bash bry-dev

WORKDIR /workspace

USER bry-dev
