services:
  sandbox-py:
    build:
      context: .
      dockerfile: container/Containerfile
    container_name: sandbox-py
    image: sandbox-py:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace
